spring:
  datasource:
    url: jdbc:h2:tcp://localhost/~/reserve
    username: sa
    password:
    driver-class-name: org.h2.Driver

  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        format_sql: true
        default_batch_fetch_size: 100

  devtools:
    restart:
      enabled: false

  profiles:
    include: oauth

logging:
  level:
    org.hibernate.SQL: debug
    org.hibernate.type: trace